# Exercise 4

Apache SpamAssasin dataset

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

## Getting the data

In [2]:
import tarfile
from pathlib import Path
import urllib.request

def fetch_spam_data():
    spam_root = "http://spamassassin.apache.org/old/publiccorpus/"
    ham_url = spam_root + "20030228_easy_ham.tar.bz2"
    spam_url = spam_root + "20030228_spam.tar.bz2"

    spam_path = Path() / ".." / "data" / "spam"
    spam_path.mkdir(parents=True, exist_ok=True)
    for dir_name, tar_name, url in (("easy_ham", "ham", ham_url),
                                    ("spam", "spam", spam_url)):
        if not (spam_path / dir_name).is_dir():
            path = (spam_path / tar_name).with_suffix(".tar.bz2")
            print("Downloading", path)
            urllib.request.urlretrieve(url, path)
            tar_bz2_file = tarfile.open(path)
            tar_bz2_file.extractall(path=spam_path)
            tar_bz2_file.close()
    return [spam_path / dir_name for dir_name in ("easy_ham", "spam")]

In [3]:
ham_dir, spam_dir = fetch_spam_data()

In [4]:
def load_spam_data(directory):
    emails = []
    for root, _, files in os.walk(directory):
            for file in files:
                file_path = os.path.join(root, file)
                with open(file_path, "r", encoding="latin1") as email_file:
                    emails.append(email_file.read())
    return emails

In [5]:
ham_data = load_spam_data(ham_dir)
spam_data = load_spam_data(spam_dir)

print(f"Number of spam emails: {len(spam_data)}")
print(f"Number of ham emails: {len(ham_data)}")

Number of spam emails: 501
Number of ham emails: 2501

In [6]:
type(ham_data[0])

str

In [7]:
def create_email_dataframe(emails, label):
    df = pd.DataFrame({
        "Email": emails,
        "Label": label
    })
    return df

ham_df = create_email_dataframe(ham_data,  0)
spam_df = create_email_dataframe(spam_data, 1)

email_df = pd.concat([ham_df, spam_df], ignore_index=True)

email_df.sample(10)

                                                  Email  Label
731   From fork-admin@xent.com  Mon Sep 30 19:59:02 ...      0
2682  From jenniferc@softhome.net  Tue Sep  3 22:25:...      1
2328  From spamassassin-talk-admin@lists.sourceforge...      0
797   From exmh-workers-admin@redhat.com  Wed Aug 28...      0
1929  From rssfeeds@jmason.org  Thu Oct  3 12:24:20 ...      0
1430  From razor-users-admin@lists.sourceforge.net  ...      0
271   From rssfeeds@jmason.org  Mon Oct  7 12:05:41 ...      0
1044  From razor-users-admin@lists.sourceforge.net  ...      0
2948  From social-admin@linux.ie  Tue Sep 24 12:53:5...      1
1228  From 0xdeadbeef-request@petting-zoo.net  Wed O...      0

In [8]:
for i in range (2500, 2511):
    print(email_df.loc[i, "Label"])

0
1
1
1
1
1
1
1
1
1
1

In [9]:
# shuffeling the data

email_df = email_df.sample(frac=1, random_state=42)
email_df.shape

(3002, 2)

In [10]:
email_df

                                                  Email  Label
2786  From safety33o@l8.newnamedns.com  Mon Aug 26 2...      1
2148  From exmh-workers-admin@redhat.com  Tue Aug 27...      0
1410  From tips@spesh.com  Mon Sep  2 12:29:16 2002\...      0
251   From ilug-admin@linux.ie  Wed Oct  9 10:54:31 ...      0
2506  From samurislugs1647k84@yahoo.com  Mon Sep  2 ...      1
...                                                 ...    ...
1638  From irregulars-admin@tb.tf  Sat Oct  5 12:38:...      0
1095  From sentto-2242572-56028-1034088521-zzzz=spam...      0
1130  From rssfeeds@jmason.org  Sat Oct  5 10:37:26 ...      0
1294  From fork-admin@xent.com  Mon Sep 30 17:56:37 ...      0
860   From rssfeeds@jmason.org  Tue Sep 24 10:47:24 ...      0

[3002 rows x 2 columns]

In [11]:
# Splitting the dataset into X and y

X = email_df.loc[:, "Email"]
y = email_df.loc[:, "Label"]

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

Shape of X: (3002,)
Shape of y: (3002,)

### Preprocessing the data

*Preprocessing steps:*
- lower casing
- removal of punctuations
- removal of stopwords
- removal of frequent words
- stemming
- lemmatisation
- conversion of emoticons to words
- removal of words
- removal of html tags
- spelling correction
- removal of rare words

In [12]:
# lower casing

X_lower = X.apply(str.lower)

In [13]:
# removal of punctuation
# string.puntuation = {!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~}

import string 

def remove_punctuation(text):
    return "".join([ch if ch not in string.punctuation else " " for ch in text])

X_lower_nopunc = X_lower.apply(remove_punctuation)

In [14]:
# removal of stopwords
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import WhitespaceTokenizer

nltk.download("stopwords")
stop_words = set(stopwords.words("english"))

def tokenization(text):
    tk = WhitespaceTokenizer()
    return tk.tokenize(text)

def remove_stopwords(text):
    return [token for token in text if token not in stop_words]

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/finnferchau/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [15]:
X_lower_nopunc_token = X_lower_nopunc.apply(tokenization)
X_lower_nopunc_token_nostopw = X_lower_nopunc_token.apply(remove_stopwords)

In [16]:
# removal of frequent words. Alternative to removing stopwords.

from collections import Counter
cnt = Counter()
for text in X_lower_nopunc_token:
    for word in text:
        cnt[word] += 1

In [17]:
frequent_words = set([w for (w, wc) in cnt.most_common(20)])

def remove_frequent_words(text):
    return [token for token in text if token not in frequent_words]

In [18]:
X_lower_nopunc_token_nofreqw = X_lower_nopunc_token.apply(remove_frequent_words)

In [19]:
# removal of rare words

n_rare_words = 200
rare_words = set([w for (w, wc) in cnt.most_common()[len(cnt.most_common())-n_rare_words:]])

def remove_rare_words(text):
    return [word for word in text if word not in rare_words]

In [20]:
X_lower_nopunc_token_nofreqw_norarew = X_lower_nopunc_token_nofreqw.apply(remove_rare_words)

In [21]:
# Stemming

from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()
def stem_words(text):
    return [stemmer.stem(word) for word in text]

In [22]:
text = ["happier", "dog", "bye", "misserable", "running"]
print(stem_words(text))

['happier', 'dog', 'bye', 'misser', 'run']

In [23]:
# lemmatization 

from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    return [lemmatizer.lemmatize(word) for word in text]

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/finnferchau/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [24]:
text = ["happier", "dogs", "best", "sources", "running"]
print(lemmatize_words(text))

['happier', 'dog', 'best', 'source', 'running']

**Preprocessing Pipeline Order**
1. Lower casing
2. Replacing URLs with "URL"
3. Replacing numbers with "Number"
4. Replacing emoticons with words
5. Removal of html tags
6. Removal of punctuation
7. Tokenization
8. Lemmatization
9. Removal of frequent words
10. Removal of rare words

In [25]:
import re
import string
from nltk.stem import WordNetLemmatizer

def replace_urls(text):
    url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
    return re.sub(url_pattern, 'URL', text)

def replace_numbers(text):
    number_pattern = r'\d+'
    return re.sub(number_pattern, 'NUMBER', text)

def replace_emoticons(text):
    emoticons = {
        ':)': 'smile',
        ':(': 'sad',
        ':D': 'grin',
        ':P': 'playful',
        ':-)': 'smile',
        ':-(': 'sad',
    }
    pattern = re.compile('|'.join(re.escape(emoticon) for emoticon in emoticons.keys()))
    return pattern.sub(lambda match: emoticons[match.group(0)], text)

def remove_html_tags(text):
    return re.sub(r'<.*?>', '', text)

def remove_punctuation(text):
    return "".join([ch if ch not in string.punctuation else " " for ch in text])

lemmatizer = WordNetLemmatizer()
def lemmatize_words(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

def preprocess_email(email:str):
    text = email.lower() # lower casing
    text = replace_urls(text) # replacing URLs
    text = replace_numbers(text) # replacing numbers 
    text = replace_emoticons(text) # replacing emoticons
    text = remove_html_tags(text) # removing html tags
    text = remove_punctuation(text) # removing punctuation
    tokens = text.split(" ") # tokenization with " "
    tokens = lemmatize_words(tokens) # lemmatization

In [137]:
from nltk import word_tokenize

nltk.download('punkt_tab')

class TextPreprocessingSteps:
    def __init__(self, X):
        self.X = X
        self.url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
        self.lemmatizer = WordNetLemmatizer()
        self.emoticons = {
            ':)': 'smile',
            ':(': 'sad',
            ':D': 'grin',
            ':P': 'playful',
            ':-)': 'smile',
            ':-(': 'sad',
        }
        self.pattern = re.compile('|'.join(re.escape(emoticon) for emoticon in self.emoticons.keys()))

    def to_lower(self):
        self.X = self.X.apply(str.lower)
        return self

    def replace_urls(self):
        self.X = self.X.apply(lambda X: re.sub(self.url_pattern, ' URL ', X))
        return self

    def replace_numbers(self):
        """
        number_pattern = r'\s\d+\s'
        self.X = self.X.apply(lambda X: re.sub(number_pattern, ' NUMBER ', X))
        return self
        """
        self.X = self.X.apply(lambda x: ['NUMBER' if word.isnumeric() else word for word in x])
        return self
    
    def replace_emoticons(self):
        self.X = self.X.apply(lambda X: self.pattern.sub(lambda match: self.emoticons[match.group(0)], X))
        return self

    def replace_emails(self):
        email_pattern = re.compile(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+")
        self.X = self.X.apply(lambda X: re.sub(email_pattern, ' EMAIL ', str(X)))
        return self
    
    def remove_html_tags(self):
        self.X = self.X.apply(lambda X: re.sub(r'<.*?>', '', X)) 
        return self
    
    def remove_punctuation(self):
        self.X = self.X.apply(lambda X: "".join([ch if ch not in string.punctuation else " " for ch in X])) 
        return self

    def tokenize(self):
        self.X = self.X.apply(word_tokenize)
        return self
    
    def lemmatize_words(self):
        self.X = self.X.apply(lambda X: [self.lemmatizer.lemmatize(word) for word in X]) 
        return self

    def remove_frequent_words(self, frequent_words):
        self.X = self.X.apply(lambda X: [word for word in X if word not in frequent_words])
        return self

    def remove_rare_words(self, rare_words):
        self.X = self.X.apply(lambda X: [word for word in X if word not in rare_words])
        return self

    def get_X(self):
        return self.X

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/finnferchau/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [197]:
# custom transformer for removing frequent and rare words

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils.validation import check_array, check_is_fitted
from collections import Counter
cnt = Counter()
for text in X_lower_nopunc_token:
    for word in text:
        cnt[word] += 1

class TextPreprocessingTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, n_frequent_words, n_rare_words):
        self.n_frequent_words = n_frequent_words
        self.n_rare_words = n_rare_words

    def fit(self, X, y=None):
        #X = check_array(X, dtype=object)
        self.n_features_in_ = X.shape[1]
        return self

    def transform(self, X, y=None):
        check_is_fitted(self)
        #X = check_array(X, dtype=object)
        assert self.n_features_in_ == X.shape[1]
        preprocessing_steps = TextPreprocessingSteps(X.loc[:, "Email"])
        X = preprocessing_steps.\
            to_lower().\
            replace_emails().\
            replace_urls().\
            replace_emoticons().\
            remove_html_tags().\
            remove_punctuation().\
            tokenize().\
            replace_numbers().\
            lemmatize_words().\
        get_X()
        cnt = Counter() # Use the token list of every row to calculate frequent and rare words
        
        for text in X:
            for token in text:
                cnt[token] += 1
        print(f'Number of distict words: {len(cnt.items())}')
        self.FREQUENT_WORDS_ = set([w for (w, wc) in cnt.most_common(self.n_frequent_words)])
        self.RARE_WORDS_ = set([w for (w, wc) in cnt.most_common()[len(cnt.most_common())-self.n_rare_words:]])
        # print(f'Frequent Words: {self.FREQUENT_WORDS_}')
        # print(f'Rare Words: {self.RARE_WORDS_}')
        X = preprocessing_steps.\
            remove_frequent_words(self.FREQUENT_WORDS_).\
            remove_rare_words(self.RARE_WORDS_).\
            get_X()
        return pd.DataFrame(X)

In [204]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

preprocessing = Pipeline([
    ("freqRareWordRomover", TextPreprocessingTransformer(20, 4000))
])

In [205]:
X_df = pd.DataFrame(X)
X_df.shape

(3002, 1)

In [206]:
df = pd.DataFrame(['hallo das ist eine 1234 Zahl', 'Das ist ein :) smiley', 'Das ist eine https://www.nltk.org/data.html URL', 'Das ist eine dieckmann245@dirk.com.de'], columns=["Email"])
df_preprocessed = preprocessing.fit_transform(df)
df_preprocessed

Number of distict words: 12

  Email
0    []
1    []
2    []
3    []

In [207]:
preprocessed_emails = preprocessing.fit_transform(X_df)

Number of distict words: 74811

In [208]:
X.iloc[1]

'From exmh-workers-admin@redhat.com  Tue Aug 27 00:00:58 2002\nReturn-Path: <exmh-workers-admin@spamassassin.taint.org>\nDelivered-To: yyyy@localhost.netnoteinc.com\nReceived: from localhost (localhost [127.0.0.1])\n\tby phobos.labs.netnoteinc.com (Postfix) with ESMTP id 2F5D043F9B\n\tfor <jm@localhost>; Mon, 26 Aug 2002 19:00:58 -0400 (EDT)\nReceived: from phobos [127.0.0.1]\n\tby localhost with IMAP (fetchmail-5.9.0)\n\tfor jm@localhost (single-drop); Tue, 27 Aug 2002 00:00:58 +0100 (IST)\nReceived: from listman.spamassassin.taint.org (listman.spamassassin.taint.org [66.187.233.211]) by\n    dogma.slashnull.org (8.11.6/8.11.6) with ESMTP id g7QMsVZ13137 for\n    <jm-exmh@jmason.org>; Mon, 26 Aug 2002 23:54:32 +0100\nReceived: from listman.spamassassin.taint.org (localhost.localdomain [127.0.0.1]) by\n    listman.redhat.com (Postfix) with ESMTP id 596833F0F3; Mon, 26 Aug 2002\n    18:54:37 -0400 (EDT)\nDelivered-To: exmh-workers@listman.spamassassin.taint.org\nReceived: from int-mx1.corp.spamassassin.taint.org (int-mx1.corp.spamassassin.taint.org\n    [172.16.52.254]) by listman.redhat.com (Postfix) with ESMTP id 1AA623F9F3\n    for <exmh-workers@listman.redhat.com>; Mon, 26 Aug 2002 18:45:13 -0400\n    (EDT)\nReceived: (from mail@localhost) by int-mx1.corp.spamassassin.taint.org (8.11.6/8.11.6)\n    id g7QMj9S03166 for exmh-workers@listman.redhat.com; Mon, 26 Aug 2002\n    18:45:09 -0400\nReceived: from mx1.spamassassin.taint.org (mx1.spamassassin.taint.org [172.16.48.31]) by\n    int-mx1.corp.redhat.com (8.11.6/8.11.6) with SMTP id g7QMj9Y03162 for\n    <exmh-workers@redhat.com>; Mon, 26 Aug 2002 18:45:09 -0400\nReceived: from austin-jump.vircio.com (jump-austin.vircio.com\n    [192.12.3.99]) by mx1.redhat.com (8.11.6/8.11.6) with SMTP id g7QMUFl20693\n    for <exmh-workers@redhat.com>; Mon, 26 Aug 2002 18:30:15 -0400\nReceived: (qmail 5815 invoked by uid 104); 26 Aug 2002 22:45:09 -0000\nReceived: from cwg-exmh@DeepEddy.Com by localhost.localdomain with\n    qmail-scanner-0.90 (uvscan: v4.1.60/v4219. . Clean. Processed in 0.363928\n    secs); 26/08/2002 17:45:08\nReceived: from deepeddy.vircio.com (@[10.1.2.1]) (envelope-sender\n    <cwg-exmh@DeepEddy.Com>) by austin-jump.vircio.com (qmail-ldap-1.03) with\n    SMTP for <exmh-workers@redhat.com>; 26 Aug 2002 22:45:08 -0000\nReceived: (qmail 6638 invoked from network); 26 Aug 2002 22:45:05 -0000\nReceived: from localhost (HELO deepeddy.vircio.com)\n    (?mUS5Vc4pF2qLz/mLmfOBxJqd0SxJJKFu?@[127.0.0.1]) (envelope-sender\n    <cwg-exmh@DeepEddy.Com>) by localhost (qmail-ldap-1.03) with SMTP for\n    <exmh-workers@redhat.com>; 26 Aug 2002 22:45:05 -0000\nX-Mailer: exmh version 2.5 07/13/2001 with nmh-1.0.4\nTo: Anders Eriksson <aeriksson@fastmail.fm>\nCc: exmh-workers@spamassassin.taint.org\nSubject: Re: Exmh && speed\nIn-Reply-To: <20020826223448.0009A3F21@milou.dyndns.org>\nReferences: <20020826223448.0009A3F21@milou.dyndns.org>\nX-Url: http://www.DeepEddy.Com/~cwg\nX-Image-Url: http://www.DeepEddy.Com/~cwg/chris.gif\nMIME-Version: 1.0\nContent-Type: multipart/signed;\n    boundary="==_Exmh_-1977488590P";\n    micalg=pgp-sha1;\n    protocol="application/pgp-signature"\nContent-Transfer-Encoding: 7bit\nMessage-Id: <1030401904.6628.TMDA@deepeddy.vircio.com>\nFrom: Chris Garrigues <cwg-exmh@DeepEddy.Com>\nX-Delivery-Agent: TMDA/0.57\nReply-To: Chris Garrigues <cwg-dated-1030833905.819ead@DeepEddy.Com>\nX-Loop: exmh-workers@spamassassin.taint.org\nSender: exmh-workers-admin@spamassassin.taint.org\nErrors-To: exmh-workers-admin@spamassassin.taint.org\nX-Beenthere: exmh-workers@spamassassin.taint.org\nX-Mailman-Version: 2.0.1\nPrecedence: bulk\nList-Help: <mailto:exmh-workers-request@spamassassin.taint.org?subject=help>\nList-Post: <mailto:exmh-workers@spamassassin.taint.org>\nList-Subscribe: <https://listman.spamassassin.taint.org/mailman/listinfo/exmh-workers>,\n    <mailto:exmh-workers-request@redhat.com?subject=subscribe>\nList-Id: Discussion list for EXMH developers <exmh-workers.spamassassin.taint.org>\nList-Unsubscribe: <https://listman.spamassassin.taint.org/mailman/listinfo/exmh-workers>,\n    <mailto:exmh-workers-request@redhat.com?subject=unsubscribe>\nList-Archive: <https://listman.spamassassin.taint.org/mailman/private/exmh-workers/>\nDate: Mon, 26 Aug 2002 17:45:03 -0500\n\n--==_Exmh_-1977488590P\nContent-Type: text/plain; charset=us-ascii\n\n> From:  Anders Eriksson <aeriksson@fastmail.fm>\n> Date:  Tue, 27 Aug 2002 00:34:43 +0200\n>\n> Just one more info. I measured the time spent wrapping the stuff in \n> Ftoc_Next with time {} so the data is for real. One difference \n> between mine and Valdis\' setup (judging from his trace) is that I use \n> the address book. I\'ve been doing that for ages so that can\'t be the \n> problem.\n\nAssuming it\'s my fault (which it probably is since nobody else has really been \nin there), it\'s most likely related to the number of sequences in a folder.  \nI\'d guess that something is either being called that shouldn\'t be or is being \ncalled more times than it should be.\n\n> Is there a way to get the log to print time with higher granularity?\n\nNot that I\'m aware of.  If you look in the code, there are various places \nwhere the time function is called in order to see how long it took to do \nthings.  You\'ll probably want to borrow that technique.\n\nChris\n\n-- \nChris Garrigues                 http://www.DeepEddy.Com/~cwg/\nvirCIO                          http://www.virCIO.Com\n716 Congress, Suite 200\nAustin, TX  78701\t\t+1 512 374 0500\n\n  World War III:  The Wrong-Doers Vs. the Evil-Doers.\n\n\n\n\n--==_Exmh_-1977488590P\nContent-Type: application/pgp-signature\n\n-----BEGIN PGP SIGNATURE-----\nVersion: GnuPG v1.0.6 (GNU/Linux)\nComment: Exmh version 2.2_20000822 06/23/2000\n\niD8DBQE9aq9vK9b4h5R0IUIRAkZrAJ4uCzn3j+5JlaqhDeEOVBMZlSATqwCdGO8z\ngy5px3yMpRraa8JkwHRwmM0=\n=fGBe\n-----END PGP SIGNATURE-----\n\n--==_Exmh_-1977488590P--\n\n\n\n_______________________________________________\nExmh-workers mailing list\nExmh-workers@redhat.com\nhttps://listman.redhat.com/mailman/listinfo/exmh-workers\n\n'

In [209]:
preprocessed_emails.loc[1, 'Email']

['mon',
 'return',
 'path',
 'delivered',
 'jalapeno',
 'jmason',
 'org',
 'postfix',
 'mon',
 'ist',
 'jalapeno',
 'imap',
 'fetchmail',
 'jm',
 'single',
 'drop',
 'mon',
 'ist',
 'auth02',
 'nl',
 'egwn',
 'net',
 'auth02',
 'nl',
 'egwn',
 'net',
 'dogma',
 'slashnull',
 'org',
 'fri',
 'feb',
 'gmt',
 'auth02',
 'nl',
 'egwn',
 'net',
 'auth02',
 'nl',
 'egwn',
 'net',
 'egwn',
 'fri',
 'feb',
 'drone4',
 'qsi',
 'net',
 'nz',
 'drone4',
 'svc',
 'skyt',
 'qsi',
 'net',
 'nz',
 'auth02',
 'nl',
 'egwn',
 'net',
 'egwn',
 'smtp',
 'fri',
 'feb',
 'qmail',
 'invoked',
 'uid',
 'feb',
 'unknown',
 'helo',
 'se7en',
 'org',
 'envelope',
 'sender',
 'qmail',
 'ldap',
 'smtp',
 'feb',
 'spawn',
 'se7en',
 'org',
 'se7en',
 'org',
 'exim',
 'debian',
 'sat',
 'feb',
 'mark',
 'derricutt',
 'subject',
 'problem',
 'apt',
 'update',
 'message',
 'mailer',
 'mulberry',
 'linux',
 'x86',
 'mime',
 'version',
 'content',
 'type',
 'text',
 'plain',
 'charset',
 'u',
 'ascii',
 'format',
 'flowed',
 'content',
 'transfer',
 'encoding',
 '7bit',
 'content',
 'disposition',
 'inline',
 'sender',
 'error',
 'beenthere',
 'mailman',
 'version',
 'precedence',
 'bulk',
 'reply',
 'help',
 'post',
 'subscribe',
 'freshrpms',
 'rpm',
 'discussion',
 'unsubscribe',
 'archive',
 'original',
 'date',
 'sat',
 'feb',
 'date',
 'sat',
 'feb',
 'hiya',
 'i',
 'always',
 'seem',
 'get',
 'error',
 'when',
 'i',
 'do',
 'an',
 'apt',
 'update',
 'is',
 'this',
 'problem',
 'on',
 'repository',
 'itself',
 'or',
 'on',
 'my',
 'end',
 'or',
 'possibly',
 'timeout',
 'connection',
 'due',
 'my',
 'connection',
 'being',
 'crappy',
 'modem',
 'root',
 'spawn',
 'root',
 'apt',
 'get',
 'update',
 'hit',
 'redhat',
 'i386',
 'base',
 'pkglist',
 'gnomehide',
 'hit',
 'redhat',
 'i386',
 'base',
 'pkglist',
 'o',
 'ign',
 'redhat',
 'i386',
 'release',
 'o',
 'err',
 'redhat',
 'i386',
 'base',
 'pkglist',
 'update',
 'bad',
 'header',
 'line',
 'hit',
 'redhat',
 'i386',
 'release',
 'update',
 'err',
 'redhat',
 'i386',
 'base',
 'pkglist',
 'freshrpms',
 'bad',
 'request',
 'err',
 'redhat',
 'i386',
 'release',
 'freshrpms',
 'bad',
 'header',
 'line',
 'hit',
 'redhat',
 'i386',
 'base',
 'srclist',
 'freshrpms',
 'ign',
 'redhat',
 'i386',
 'release',
 'gnomehide',
 'ign',
 'redhat',
 'i386',
 'base',
 'mirror',
 'hit',
 'redhat',
 'i386',
 'release',
 'freshrpms',
 'ign',
 'redhat',
 'i386',
 'base',
 'mirror',
 'ign',
 'redhat',
 'i386',
 'base',
 'mirror',
 'ign',
 'redhat',
 'i386',
 'base',
 'mirror',
 'ign',
 'redhat',
 'i386',
 'base',
 'mirror',
 'failed',
 'fetch',
 'bad',
 'header',
 'line',
 'failed',
 'fetch',
 'bad',
 'request',
 'failed',
 'fetch',
 'bad',
 'header',
 'line',
 'm',
 'if',
 'i',
 'seem',
 'super',
 'human',
 'i',
 'have',
 'been',
 'misunderstood',
 'c',
 'dream',
 'theater',
 'icq',
 'jid',
 'rpm',
 'mailing']